on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create environment
        run: vite
        
      - name: linting
        run: eslint --ext .jsx --fix src

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: testing
        run: vitest run

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: building
        run: vite build